= 🇫🇷 Support de cours pour le module devops, sous section docker

Cours disponible à cette adresse : https://gounthar.github.io/cours-devops-docker/main[]

🇺🇸

This repository hosts the source of the slide decks.

Slides are written in https://asciidoctor.org/[Asciidoctor language] and rendered as HTML and PDF using https://revealjs.com/[reveal.js].

== How-to Work with this Presentation?

=== Requirements

* You need:
** Docker CE 20.10+ (with local bind-mount capability -
Docker Desktop or a local Linux Docker CE install)
** https://www.gnu.org/software/make/[GNU Make] in your `PATH`

== Generate the slides

* If you want to generate the slide-deck in "one shot":
** Clone the repository
** Run the following `make` command:

[source,bash]
----
make build
----

** Open the resulting file `./dist/index.html`

=== Working on the slides with Live-reloading

* If you want to build and serve the slides locally,
with a live-reloading capability
(e.g. change a `*.adoc`, regenerate the HTML and reload the web-browser)
to get a WYSIWYG experience:

** Clone the repository
** Run the following `make` command:
+
[source,bash]
----
make serve
----

** Open the URL link:http://localhost:8000
** Edit one of the `*.adoc` file, save it, and see the page reload
*** it is valid for images and styles also

=== Run checks on the generated HTML

You can validate the HTTP links and the HTML's w3c compliance
of the generated slide deck.

If you already generated the file `./dist/index.html`,
then run the following `make` command:

[source,bash]
----
make verify
----

Otherwise, you can run the `all` command ,as the CI process is doing:

[source,bash]
----
make all
----

=== Dependencies management

As NPM is used for expressing the dependencies, you can execute the following chores:

* Lock the dependencies (e.g. generating the file `package-lock.json` from the file `package.json` and the content of `nodes_modules`):

[source,bash]
----
make dependencies-lock-update
----

* Upgrade all dependencies (e.g. update the file `package.json`)

[source,bash]
----
make dependencies-update
----

=== Maintenance tasks inside the container

If you want to get a shell inside the "build and serve" container,
run the following `make` command:

[source,bash]
----
make shell
----

==== Example: Updating the package.json (and package-lock.json) Dependencies

[source,bash]
----
$ make shell
# Update the `package.json` file to latest versions
/app > ncu -u
# Update the `package-lock.json` file from `package.json`
/app > npm install
----

== CI/CD

- GitHub Actions are used to continuously build, validate and deploy the changes on this slides.
- GitHub Page is used to serve the generated HTML and PDF content (deployment target).
