diff --git a/src/Dockerfile b/src/Dockerfile
index c92c67c..77919a5 100644
--- a/src/Dockerfile
+++ b/src/Dockerfile
@@ -11,2 +11,6 @@ EXPOSE 4321
 
+RUN adduser --disabled-password --gecos "" --home /home/www www
+USER www
+WORKDIR /home/www
+
 ENTRYPOINT ["/bin/start.sh"]
